import type { HelpRequest } from "@/lib/types"

export const DEMO_HELPEE = {
  name: "Alya",
  email: "alya@gmail.com",
  rating: 4.8,
  ratingsCount: 10,
  tasksCompleted: 15,
  onTimeRate: 97,
  walletBalance: 150000,
}

export const DEMO_HELPER = {
  name: "Raka",
  email: "raka@gmail.com",
  rating: 4.9,
  ratingsCount: 132,
  tasksCompleted: 214,
  onTimeRate: 98,
  walletBalance: 85000,
}

export const SEED_REQUESTS: HelpRequest[] = [
  {
    id: "1",
    title: "Buy lunch from FEB canteen",
    description:
      "Nasi padang with extra sambal. Pick up from FEB canteen and deliver to Jatinangor dorm block B.",
    priceMin: 15000,
    priceMax: 25000,
    status: "open",
    category: "Food run",
    location: "FEB · Jatinangor",
    estimatedDuration: "~20 min",
    photoUrl: "/images/task-1.webp",
    helpee: {
      name: "Dimas",
      email: "dimas@gmail.com",
      rating: 4.6,
      ratingsCount: 14,
      tasksCompleted: 20,
      onTimeRate: 95,
    },
    createdAt: new Date(Date.now() - 4 * 60 * 1000),
  },
  {
    id: "2",
    title: "Deliver package to Jatinangor dorm",
    description:
      "Small package from the Nangor post office. Needs to reach dorm block C before 5pm today.",
    priceMin: 20000,
    priceMax: 30000,
    status: "open",
    category: "Moving",
    location: "Post office · 0.6 mi",
    urgent: true,
    estimatedDuration: "~45 min",
    photoUrl: "/images/task-2.webp",
    helpee: {
      name: "Sinta",
      email: "sinta@gmail.com",
      rating: 4.7,
      ratingsCount: 9,
      tasksCompleted: 8,
      onTimeRate: 99,
    },
    createdAt: new Date(Date.now() - 18 * 60 * 1000),
  },
  {
    id: "3",
    title: "Help format thesis bibliography",
    description:
      "Need help formatting bibliography in APA 7th edition. About 40 references in a Word document.",
    priceMin: 50000,
    priceMax: 80000,
    status: "open",
    category: "Tutoring",
    location: "FEB Library · tonight",
    estimatedDuration: "~2 hours",
    photoUrl: "/images/task-3.webp",
    helpee: {
      name: "Bima",
      email: "bima@gmail.com",
      rating: 4.5,
      ratingsCount: 22,
      tasksCompleted: 18,
      onTimeRate: 92,
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "4",
    title: "Pick up parcel from JNE Jatinangor",
    description:
      "Please pick up my online shopping package from the JNE Jatinangor branch. The package is under the name Siska. Deliver to the lobby of Pinewood Apartment.",
    priceMin: 15000,
    priceMax: 25000,
    status: "open",
    category: "General",
    location: "JNE Jatinangor to Pinewood",
    estimatedDuration: "~30 min",
    photoUrl: "/images/task-4.webp",
    helpee: {
      name: "Siska",
      email: "siska@gmail.com",
      rating: 4.9,
      ratingsCount: 15,
      tasksCompleted: 12,
      onTimeRate: 98,
    },
    createdAt: new Date(Date.now() - 35 * 60 * 1000),
  },
  {
    id: "5",
    title: "Help moving wooden wardrobe inside Kos",
    description:
      "Need help lifting and moving a medium wooden wardrobe from the 1st floor to my new room on the 3rd floor at Kos Ganesha. I can help carry too.",
    priceMin: 40000,
    priceMax: 60000,
    status: "open",
    category: "Moving",
    location: "Kos Ganesha, Sukawening",
    estimatedDuration: "~40 min",
    photoUrl: "/images/task-5.webp",
    helpee: {
      name: "Rian",
      email: "rian@gmail.com",
      rating: 4.8,
      ratingsCount: 6,
      tasksCompleted: 4,
      onTimeRate: 100,
    },
    createdAt: new Date(Date.now() - 50 * 60 * 1000),
  },
  {
    id: "6",
    title: "Buy cold medicine from Apotek K-24",
    description:
      "I have a high fever and cannot leave my bed. Please buy paracetamol and vitamins from Apotek K-24 Jatinangor and deliver to Dorm Block A.",
    priceMin: 15000,
    priceMax: 20000,
    status: "open",
    category: "General",
    location: "Apotek K-24 to Dorm Block A",
    urgent: true,
    estimatedDuration: "~25 min",
    photoUrl: "/images/task-6.webp",
    helpee: {
      name: "Fitri",
      email: "fitri@gmail.com",
      rating: 4.7,
      ratingsCount: 11,
      tasksCompleted: 9,
      onTimeRate: 94,
    },
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "7",
    title: "Peer tutoring for Java Programming",
    description:
      "Struggling with object-oriented concepts and arrays in Java. Need a 2-hour tutoring session at a cafe near Unpad. Coffee is on me!",
    priceMin: 60000,
    priceMax: 90000,
    status: "open",
    category: "Tutoring",
    location: "Cozy Cafe Jatinangor",
    estimatedDuration: "~2 hours",
    photoUrl: "/images/task-7.webp",
    helpee: {
      name: "Andi",
      email: "andi@gmail.com",
      rating: 4.4,
      ratingsCount: 30,
      tasksCompleted: 25,
      onTimeRate: 90,
    },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: "8",
    title: "Print and bind chemistry lab report",
    description:
      "I need 25 pages of my chemistry lab report printed in color, spiral-bound, and delivered to the Science Faculty main lobby by 8:30 AM tomorrow.",
    priceMin: 20000,
    priceMax: 30000,
    status: "open",
    category: "General",
    location: "Science Faculty Main Lobby",
    estimatedDuration: "~30 min",
    photoUrl: "/images/task-8.webp",
    helpee: {
      name: "Nadia",
      email: "nadia@gmail.com",
      rating: 4.9,
      ratingsCount: 4,
      tasksCompleted: 3,
      onTimeRate: 100,
    },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "9",
    title: "Deliver Kopi Kenangan to Hegarmanah",
    description:
      "Please buy 2 cups of Iced Kopi Susu Tetangga from Kopi Kenangan Jatinangor and deliver them to Hegarmanah boarding houses.",
    priceMin: 10000,
    priceMax: 18000,
    status: "open",
    category: "Food run",
    location: "Kopi Kenangan to Hegarmanah",
    estimatedDuration: "~15 min",
    helpee: {
      name: "Rizky",
      email: "rizky@gmail.com",
      rating: 4.7,
      ratingsCount: 20,
      tasksCompleted: 15,
      onTimeRate: 96,
    },
    createdAt: new Date(Date.now() - 8 * 60 * 1000),
  },
]
